config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :links, only: [:create]
  get '/not_found', to: 'pages#not_found'
  get '/:token/info', to: 'links#info', as: 'link_info'
  get '/:token', to: 'links#show', as: 'show_link'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates_presence_of :long_url, :token

  validates_uniqueness_of :token
end

app/models/link_visit.rb
class LinkVisit
  include Mongoid::Document
  include Mongoid::Timestamps

  field :token, type: String

  field :ip_address, type: String
  field :country_code, type: String
  field :referer, type: String

  index({ token: 1 })

  validates_presence_of :ip_address, :token

  def self.count_group_by(attr)
    map = %Q(
      function() {
        key = this.#{attr};
        value = { count: 1};
        emit(key, value);
      }
    )

    reduce = %Q(
      function(key, values) {
        var reducedValue = { count: 0 };
        values.forEach(function(value) {
          reducedValue.count += value.count
        });
        return reducedValue;
      }
    )

    self.map_reduce(map, reduce).out(inline: 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :set_link, only: [:show, :info]

  def show
    TrackVisit.new(@link, request).call

    if @link
      redirect_to @link.long_url
    else
      redirect_to not_found_path
    end
  end

  def info
    # @analytics = AnalyticsService.new(@link).call
    @total_visits = LinkVisit.where(token: @link.token).count
    @geo_data = generate_geo_data

  rescue ActiveRecord::RecordNotFound
    redirect_to not_found_path
  end

  def create
    @link = UrlShortener.new(link_params).call

    if @link.persisted?
      redirect_to link_info_path(@link.token)
    else
      # redirect_to root_path
    end 
  end

  private

  def set_link
    @link = Link.find_by(token: params[:token])
  end

  def link_params
    params.require(:link).permit(:long_url)
  end

  def generate_geo_data
    result = LinkVisit.where(token: @link.token).count_group_by(:country_code).execute

    result["results"].map { |r| { r["_id"] => r.dig('value', 'count') }}
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @link = Link.new
  end

  def not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/info.html.erb
<h3>URL: <%= @link.long_url %></h3>

<h3>Short URL: <%= link_to show_link_url(@link.token), show_link_url(@link.token), target: '_blank' %> </h3>

<h3>Stats:</h3>

<b>Total visits:</b> <%= @total_visits %>

<%= geo_chart @geo_data %>

app/views/pages/index.html.erb
<h3>URL Shortener</h3>

<%= form_with model: @link, url: links_path do |f| %>
  <%= f.label :long_url, "URL: "%>
  <%= f.text_field :long_url %>

  <%= f.submit 'Submit URL' %>
<% end %>

app/views/pages/not_found.html.erb
<h3>The URL was not found</h3>